config/routes.rb
ActionController::Routing::Routes.draw do |map|  

  
  map.connect "events/past", :controller => "events", :action => "past"
  map.connect "events/past.:format", :controller => "events", :action => "past"

  map.admin "admin", :namespace => "admin", :controller => "home"
  map.password_reset "users/:username/reset/:reset_hash", :controller => "users", :action => "password_reset"
  map.login "login", :controller => "sessions", :action => "new"
  map.logout "logout", :controller => "sessions", :action => "destroy"
  map.request_credentials "request_credentials", :controller => "users", :action => "request_credentials"
  map.article_diff "admin/articles/:id/compare/:rev_a/:rev_b", :namespace => "admin", :controller => "articles", :action => "compare"
  map.change_revision "admin/articles/:id/change_revision/:revision", :namespace => "admin", :controller => "articles", :action => "change_revision"
  map.categories "articles/categories/:id", :controller => "articles", :action => "categories"
  map.news_with_page "news/page/:page", :controller => "news", :action => "index"
  map.articles_with_page "articles/page/:page", :controller => "articles", :action => "index"
  map.categories_with_page "articles/categories/:id/page/:page", :controller => "articles", :action => "categories"
  map.account_activation "users/:username/activate/:activation_hash", :controller => "users", :action => "activate"
  

  
  map.resources :news
  map.resources :articles
  map.resources :events
  map.resources :galleries
  map.resources :users, :member => { :remove => :get }
  map.resources :profiles

  

  map.namespace :admin do |admin|
    admin.resources :users
    admin.resources :news, :collection => { :bulk_action => :post }
    admin.resources :articles, :collection => { :bulk_action => :post }
    admin.resources :events, :collection => { :bulk_action => :post }
    admin.resources :galleries, :collection => { :bulk_action => :post }
    admin.resources :categories
  end

  map.root :controller => "home"

  map.connect 'sitemap.:format', :controller => "sitemap", :action => "index"
  map.connect "search/opensearch.xml", :controller => "search", :action => "opensearch"
  
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :image, :class_name => "Asset"
  has_many :revisions
  has_many :categorizations
  has_many :categories, :through => :categorizations
  has_many :assets, :as => :attachable
  
  validates_presence_of :title, :description, :body
  
  named_scope :all_published, :conditions => { :published => true }, :order => "published_at DESC" # legacy scope
  named_scope :published, :conditions => { :published => true }, :order => "published_at DESC"
  named_scope :unpublished, :conditions => { :published => true }
  named_scope :for_user, lambda { |user|
      { :conditions => { :user_id => user.id } }
  }
  
  attr_accessor :updated_by_user_id
  
  def before_create
    self.current_revision_id = 1
  end
  
  def before_save
    self.published_at ||= Time.now if self.published?
  end
  
  def after_create
    Revision.create :number => 1, :title => title, :description => description, :body => body, :user_id => user_id, :article_id => id
  end
  
  def before_destroy
    return false if Setting.option("featured_article").to_i == id
  end
  
  def change_to_revision(number)
    revision = Revision.find_by_article_id_and_number(self.id, number)
    self.title = revision.title
    self.description = revision.description
    self.body = revision.body
    self.current_revision_id = number
    self.save_without_validation
  end
  
  def after_validation_on_update
    if title != current_revision.title || description != current_revision.description || body != current_revision.body
      latest_revision = Revision.maximum(:number, :conditions => "article_id = #{id}") || 0
      self.current_revision_id = latest_revision + 1
      Revision.create :number => latest_revision + 1, :title => title, :description => description, :body => body, :user_id => updated_by_user_id, :article_id => id
    end
  end
  
  def current_revision
    return Revision.find_by_article_id_and_number(id, current_revision_id)
  end
  
  def images
    Asset.images("Article", id)
  end
  
  def files
    Asset.files("Article", id)
  end
  
  def self.featured
    featured_article_id = Setting.option("featured_article")
    if featured_article_id.nil? || featured_article_id.empty?
      return nil
    else
      return Article.find(featured_article_id)
    end
  end
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
  
  def author_name
    self.user.name
  end
  
  def self.statistics
    {:total => self.count, :published => self.count(:all, :conditions => { :published => true }), :unpublished => self.count(:all, :conditions => { :published => false })}
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdministrationController  
  def index
    
    @articles = Article.find_all_for_user(current_user, :order => "id DESC")
    @featured_article = Setting.featured_article_id

    respond_to do |format|
      format.html
    end
  end

  def show
    respond_to do |format|
      format.html { redirect_to :action => "edit" }
    end
  end

  def new
    
    @article = Article.new
    @category = Category.new
    @categories = Category.all

    respond_to do |format|
      format.html
    end
  end

  def edit
    @article = Article.find(params[:id], :include => :categories)
    @category = Category.new
    @categories = Category.all
    
    respond_to do |format|
      if @article.editable?(current_user)
        format.html
      else
        format.html { redirect_to admin_articles_path }
      end
    end
  end

  def create
    @article = Article.new(params[:article])
    @article.user_id = current_user_id
    @asset = @article.assets.build(params[:asset].merge!(:user_id => current_user_id)) if params[:upload]

    if params[:create_category]
      category = Category.create!(params[:category])
      @article.categories << category
    elsif params[:destroy_category]
      category = Category.find(params[:destroy_category])
      if category.articles.empty?
        category.destroy
      else
        flash.now[:error] = "The category " + category.name + " has articles associated with it."
      end
    end
    @categories = Category.all

    respond_to do |format|
      if params[:create_category] || params[:destroy_category] || params[:preview]
        format.html { render :action => "new" }
      else
        if @article.save
          flash[:notice] = "Article successfully created."
          format.html { redirect_to edit_admin_article_path @article }
        else
          format.html { render :action => "new" }
        end
      end
    end
  end
  
  def update
    @article = Article.find(params[:id])

    redirect_to admin_articles_path and return unless @article.editable?(current_user)
    
    if params[:upload]
      @asset = @article.assets.create(params[:asset].merge!(:user_id => current_user_id))
    elsif params[:create_category]
      category = Category.create!(params[:category])
      @article.categories << category
    elsif params[:destroy_asset]
      Asset.find(params[:destroy_asset]).destroy
    elsif params[:destroy_category]
      category = Category.find(params[:destroy_category])
      if category.articles.empty?
        flash.now[:notice] = "The category '" + category.name + "' has been removed."
        category.destroy
      else
        flash.now[:error] = "The category '" + category.name + "' has articles associated with it."
      end
    elsif params[:diff]
      diff_path = article_diff_path :id => params[:id], :rev_a => params[:rev_a], :rev_b => params[:rev_b]
    end
    
    @article.attributes = params[:article]
    @categories = Category.all

    respond_to do |format|
      if params[:upload] || params[:create_category] || params[:destroy_asset] || params[:destroy_category] || params[:preview]
        format.html { render :action => "edit" }
      elsif params[:diff]
        format.html { redirect_to diff_path }
      else
        @article.updated_by_user_id = current_user_id
        if params[:image] == "nil"
          @article.image = nil
        else
          @article.image_id = params[:image]
        end
        if @article.save
          flash[:notice] = "Article was successfully updated."
          format.html { redirect_to admin_article_path(@article) }
        else
          format.html { render :action => "edit" }
        end
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    
    if current_user.role.can_delete?
      if @article.destroy
        flash[:notice] = "Article was successfully deleted."
      else
        flash[:error] = "Some error happened. The article was not deleted."
      end
    end

    respond_to do |format|
      format.html { redirect_to admin_articles_path }
    end
  end
  
  def feature
    setting = Setting.find_by_option("featured_article")
    article_to_feature = params[:id]
    
    respond_to do |format|
      if Article.find(article_to_feature).published?
        if setting.update_attribute("value", article_to_feature)
          flash[:notice] = "Article is now featured."
        else
          flash[:error] = "Something went wrong..."
        end
      else
        flash[:error] = "Cannot feature an unpublished article."
      end
      format.html { redirect_to admin_articles_url }
    end
  end
  
  def compare
    @rev_a = Revision.find_by_article_id_and_number(params[:id].to_i, params[:rev_a])
    @rev_b = Revision.find_by_article_id_and_number(params[:id].to_i, params[:rev_b])

    respond_to do |format|
      if !@rev_a.nil? && !@rev_b.nil?
        format.html { @diff = Diff.new(@rev_a.body, @rev_b.body) }
      else
        format.html { redirect_to edit_admin_article_path(:id => params[:id]) }
      end
    end
  end
  
  def change_revision
    article = Article.find(params[:id])
    
    article.change_to_revision(params[:revision]) if current_user.role.can_update? || current_user_id == article.user_id
    
    respond_to do |format|
      format.html { redirect_to edit_admin_article_path(params[:id]) }
    end
  end
  
  def bulk_action
    unless params[:articles].nil?
      selected = []
      params[:articles].each { |id, value| selected << id if value == "on" }
      articles = Article.find(selected)
      featured_article = Article.featured
    
      case params[:actions]
        when "delete"
          if articles.include? featured_article
            flash[:error] = "Cannot delete the featured article."
          else
            articles.each { |a| a.destroy } if current_user.role.can_delete?
          end
        when "publish"
          articles.each { |a| a.update_attribute(:published, true) } if current_user.role.can_publish?
        when "unpublish"
          if articles.include? featured_article
            flash[:error] = "Cannot unpublish the featured article."
          else
            articles.each { |a| a.update_attribute(:published, false) } if current_user.role.can_publish?
          end
      end
    end
    
    respond_to do |format|
      format.html { redirect_to admin_articles_path }
    end
  end
  
  def unpublish
    article = Article.find(params[:id])
    
    if article == Article.featured
      flash[:error] = "Cannot unpublish the featured article."
    else
      article.update_attribute(:published, false) if current_user.role.can_publish?
      flash[:notice] = "The article was unpublished."
    end
    
    respond_to do |format|
      format.html { redirect_to admin_articles_path }
    end
  end
  
  def publish
    article = Article.find(params[:id])
    
    article.update_attribute(:published, true) if current_user.role.can_publish?
    
    respond_to do |format|
      flash[:notice] = "The article was published."
      format.html { redirect_to admin_articles_path }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.published.paginate(:page => params[:page], :per_page => 10, :order => "published_at DESC", :include => :user)    
    @categories = Category.all_alphabetically

    respond_to do |format|
      format.html
      format.atom { @articles = Article.published.find(:all, :limit => 10, :order => "published_at DESC") }
    end
  end

  def show
    @article = Article.published.find(params[:id].to_i)
    
    respond_to do |format|
      format.html
    end
  end
  
  def categories
    @category = Category.find(params[:id])
    @articles = @category.articles.published.paginate(:page => params[:page], :per_page => 10, :order => "published_at DESC", :include => :user)    
    @categories = Category.all_alphabetically
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def cloudify(categories, min_font_size = 120, max_font_size = 180, link_css_class = "cloudLink", span_css_style = "display:inline-block;")
    xhtml = ""
    categories_array = Array.new
    
    categories.each do |c|
      count = c.published_articles.size
      categories_array.push count if count > 0
    end
    
    categories_array.sort!
    
    min_occurs = categories_array.first
    max_occurs = categories_array.last
    
    categories.each do |c|
      if c.published_articles.size > 0
        if min_occurs < max_occurs
          weight = (Math.log(c.published_articles.size) - Math.log(min_occurs)) / (Math.log(max_occurs) - Math.log(min_occurs))
          font_size_of_current_category = (min_font_size + ((max_font_size-min_font_size) * weight)).round
        else
          font_size_of_current_category = min_font_size
        end

        xhtml << "<span style=\"" + span_css_style + "\" title=\"#{ pluralize(c.published_articles.size, "article") }\">"
        xhtml << "#{link_to c.name, categories_path(c), :class => link_css_class, :style => "font-size: " + font_size_of_current_category.to_s + "%"} (" + c.published_articles.size.to_s + ") &nbsp;"
        xhtml << "</span>"
      end
    end
    
    return xhtml
  end
end

app/views/admin/articles/_categories.html.erb
<h3 class="title">Categories</h3>

<div id="categories">	
	<% if @categories.empty? %>
		<p>There are no categories at the moment. Please create one.</p>
	<% else %>
		<table>
			<% for category in @categories %>
			<tr class="<%= cycle("odd", "even") %>">
				<td>
					<%= check_box_tag "article[category_ids][]", category.id, @article.categories.include?(category) %>
					<label for="categories_<%= category.id%>"><%= category.name %></label>
				</td>
				<td>
					<%= image_submit_tag "/images/tango/16px/delete.png", :value => category.id, :name => "destroy_category", :style => "position: relative; top: 5px;", :alt => "Delete" %>
				</td>
			</tr>
			<% end %>
		</table>
	<% end %>
</div>

<% fields_for :category do |c| %>
	<p>
		<%= c.label :name, "New category" %><br />
		<%= c.text_field :name, :class => "wide" %>
	</p>

	<p>
		<%= submit_tag "Create category", :name => "create_category" %>
	</p>
<% end %>

app/views/admin/articles/_form.html.erb
<% form_for [:admin, @article], :html => { :multipart => true } do |f| %>
	<div id="editArea">
		<%= f.error_messages%>

		<% if params[:preview] %>
			<div id="preview" title="Preview">
				<h1><%= @article.title %></h1>
				<p><strong><%= @article.description %></strong></p>
				<%= textilize @article.body %>
			</div>
		<% end %>

		<p>
			<%= f.label :title %><br />
			<%= f.text_field :title, :class => "titleField", :size => 39 %>
		</p>
	
		<p>
			<%= f.label :description %><br />
			<%= f.text_field :description, :class => "wide", :size => 75 %>
		</p>
	
		<p>
			<%= f.label :body %><br />
			<%= f.text_area :body, :cols => 85, :rows => 20, :class => "textile" %>
		</p>
	</div>
	
	<div id="sidebar">
	  <%= render :partial => "admin/actions", :locals => { :f => f, :item => @article } %>
	
		<%= render :partial => "categories" %>
	</div>
	
	<%= render :partial => "admin/assets/assets", :locals => { :assetable => @article } %>
		
	<%= render :partial => "revisions" unless @article.new_record? %>
	
<% end %>

app/views/admin/articles/_revisions.html.erb
<div id="revisions">
	<h3 class="title">Revisions</h3>
	
	<table>
		<tr>
			<th>Revision</th>
			<th>From</th>
			<th>To</th>
			<th>Date</th>
			<th>User</th>
		</tr>

		<% for revision in @article.revisions.reverse %>
			<tr>
				<td>
					<%= revision.number %>
					<% if revision.number == @article.current_revision_id %>
						<strong>current</strong>
					<% else %>
						<%= link_to "change to", change_revision_path(:id => @article.id, :revision => revision.number) %>
					<% end %>
				</td>
				<td><input type="radio" name="rev_a" value="<%=h revision.number %>" /></td>
				<td><input type="radio" name="rev_b" value="<%=h revision.number %>" /></td>
				<td><%= short_date(revision.created_at) %></td>
				<td><%= revision.user.name_with_role %></td>
			</tr>
		<% end %>
	</table>

	<p><%= submit_tag "Compare", :name => "diff" %></p>
</div>

app/views/admin/articles/compare.html.erb
<% title "Comparison" %>

<h3 class="title"><%= Diff.new(@rev_a.title, @rev_b.title).to_html %></h3>

<p><%= link_to "[ back to article ]", :action => "edit", :id => params[:id] %></p>

<p style="font-weight:bold;"><%= Diff.new(@rev_a.description, @rev_b.description).to_html %></p>

<div><%= @diff.to_html %></div>

app/views/admin/articles/edit.html.erb
<% title "Editing article" %>

<%= render :partial => "form" %>

app/views/admin/articles/index.html.erb
<% title "Articles" %>

<p><%= link_to "Add article", new_admin_article_path, :class => 'add' %></p>

<% bulk_options(bulk_action_admin_articles_path) do |actions_available| %>

<table>
  <tr>
		<% if actions_available %>
	  	<th><input type="checkbox" id="bulk_check" /></th>
		<% end %>
    <th>Title</th>
    <th>Created</th>
	<th>Revision</th>
	<th>Status</th>
		<% if current_user.role.can_administer? %>
			<th>Featured</th>
		<% end %>
  </tr>

	<% for article in @articles %>
		<tr class="<%= cycle("odd", "even") %>">
			<% if actions_available %>
				<td class="checkbox"><input type="checkbox" name="articles[<%= article.id %>]" /></td>
			<% end %>
	    <td><%= link_to article.title, { :id => article.id, :action => "edit" }, { :title => "Edit", :class => "listingTitle" } %><br />
	    		<%=h truncate(article.description, :length => 50, :ommission => "...") %>
	    </td>
		  <td style="text-align: center;"><%=h short_date(article.created_at) %></td>
			<td style="text-align: center;"><%= article.current_revision_id %></td>
		  <td style="text-align: center;">
			<% if article.published? %>
				<%= link_to (image_tag("tango/22px/publish.png", :alt => "Published")), { :id => article.id, :action => "unpublish" }, { :title => "Unpublish '#{article.title}'" } %>
			<% else %>
				<%= link_to (image_tag("tango/22px/unpublish.png", :alt => "Unpublished")), { :id => article.id, :action => "publish" }, { :title => "Publish '#{article.title}'" } %>
			<% end %>
		  </td>
			<% if current_user.role.can_administer? %>
				<td style="text-align: center;">
					<% if defined? article.published && article.published %>
  					<% if article.id != @featured_article %>
    						<%= link_to image_tag("tango/22px/not_featured.png", :alt => "Feature"), { :id => article.id, :action => "feature" }, { :title => "Feature" }%>
  					<% else %>
    						<%= image_tag("tango/22px/featured.png", :alt => "Currently featured") %>
 						<% end %>
					<% end %>
					</td>
			<% end %>
	  </tr>
	<% end %>
</table>
<% end %>

app/views/admin/articles/new.html.erb
<% title "Add article" %>

<%= render :partial => "form" %>